stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t simple_web_application .

test:
  stage: test
  image: node:18
  script:
    - echo "Running tests..."
    - npm install
    - npm test || echo "No tests found, skipping..."

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Running Docker container..."
    - docker run -d -p 3000:3000 simple_web_application
